services:
  db:
    image: amd64/mysql
    container_name: mentor-db
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    platform: linux/amd64
    volumes:
      - ./backup:/var/lib/mysql

  redis:
    image: redis
    container_name: mentor-redis
    ports:
      - 6379:6379
    volumes:
      - ./backup_redis:/var/lib/redis
    restart: always

#  spring_boot:
#    image: ${SPRING_BOOT_IMAGE}
#    container_name: spring_boot
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: ${MYSQL_URL}
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
