server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  redis:
    host: localhost
    port: 6379

#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#      location: src/main/resources/files

  mvc:
    path match:
      matching-strategy: ant_path_matcher

# Hibernate
logging:
  level:
    com:
      querydsl: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        BasicBinder: TRACE

cloud:
  aws:
    s3:
      bucket:  stutino-bucket
    credentials:
      access-key: AKIA3F6XNQ75NF7264VQ
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

app:
  cors:
    # comma (',') seperated list of allowed origins for CORS
    allowed-origins: http://localhost, http://localhost:3000
